version: 2
groups:
  code-review:
    approve_by_comment:
      approve_regex: ^Approved
      enabled: true
      reject_regex: ^Rejected
    required: 6
    users:
    - BriakallistaStarfinder
    - BritanyannStarfinder
	- BruceStarfinder
    - CaseyraeStarfinder
	- EmperorStarfinder
    - IrishwolfStarfinder
	- NoahStarfinder
    - PirittaStarfinder
	- QueenStarfinder
    - TimothyStarfinder
