language: csharp

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "IANS5YpsbyaOHEFJL4luBIXBCEI6Eg0tNLHRkViJMkqZktXXeOEqXOaAKoYReP7qSGfSMpV7atKDQJhfuDqTlOIZhT9FELYE66+Y3zpuQhJ0ZxHGCG6kG9Wy+82maPMzZaZK10cFyUez5XooPZ9mt5Y4VCmfsdJAjTY5QqBcugy5KBP5IIXWNVaRTWrXXP3Q+X2q8jbU6cFUOgpgyhBSnG5BusxhLPyXkwSzpAqjQQtn3x+Xd68nHN972uTyvoKbrDpC2eTcg+H1b2FpU+OkhWAGDdiSvdorv0Y4iO5jG5uLxk3dCXQhu6axpFDlamjIUX2toKemmH2uoW3VHmELtIbvYd2bjXTVrbG9kNSzwS7HDqN9rr3sorqqOKhYBlQjORbR2gjb/lBxYvEwzPuKKBeKWqULrkkrWJICOpBf8mz1a5rDJcN4Ypdg82UonMeVhkoNp042vJD7rwUXJeA73NcdHVHPtp2yH04+tkqiGt0KwawTpWub0UBaHBif2TSX2ZlHIqRqmI1Q03wrwxWbx5CpwbyLnyqBTixVXGqEPst9nwhQKfMo1sUjTL6L5onRhoVK0XSXlXPgLAGBiZMnksuDHChENjEzk52a7p/AcM685WKAtVD8bZaeiuUMb7A83xF9g6a7hRpdTqgTNTOSnnNkOBrJQNz8K2Tsz3fI0KE="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "Virtual-Universe/Virtual-Universe-Early-Dev"
      description: "Opensource virtual world grid archictecture"
    notification_email: secondgalaxy2013@gmail.com
    build_command_prepend: "./runprebuild.sh -c Debug -a x64 -b Yes"
    build_command: "msbuild Universe.sln"
    branch_pattern: coverity_scan

mono:
  - latest
script:
  - ./runprebuild.sh -c Debug -a x64 -b Yes
notifications:
  irc:
    channels:
      - "chat.freenode.net#galaxyfutures"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
sudo: false
