version: 2.0.1.{build}
branches:
  only:
  - master
build_script:
- Prebuild.exe /target vs2015 /targetframework v4_6 /conditionals ISWIN;NET_4_6
- msbuild Universe.sln /p:Configuration=Debug  /p:DefineConstants="ISWIN;NET_4_6"
artifacts:
- path: VirtualUniverse\bin
  name: Universe